version: '3'
services:
    postgres:
        image: postgres:14.3-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: mypassword
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./backend/src:/app/src
        ports:
            - "3000:3000"
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./ui:/app
        ports:
            - "8080:3000"