version: '3'
services:
    postgres:
        image: postgres:14.3-alpine
        ports:
            - "5433:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: mypassword
            POSTGRES_USER: postgres
            POSTGRES_DB: iupidb
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
            - ./backend/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./backend/src:/app/src
        ports:
            - "3000:3000"
        depends_on:
        - postgres
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./ui:/app
        ports:
            - "8080:3000"  