FROM node:lts-alpine3.16
EXPOSE 8080 
RUN mkdir -p /app/dist /app/src

WORKDIR /app
COPY tsconfig.json /app/tsconfig.json
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY .env /app/.env

RUN npm install

CMD ["npm", "run", "dev"]