FROM node:lts-alpine3.16
EXPOSE 8080 
RUN mkdir -p /app/public /app/src

WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install --silent
RUN mkdir /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

CMD ["npm", "run", "dev"]